const express = require('express')
const moggoose = require('mongoose')
const dotenv = require('dotenv').config()
const cors = require('cors')
const app = express()
const bodyParser = require('body-parser')
const laudaryLogin = require('./routes/laudaryLogin')
const laudaryRegister = require("./routes/laudaryRegister")

app.use(cors())
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended:false}))
app.use('/laudary',laudaryLogin)
app.use('/laudary/register',laudaryRegister)
app.post('/',(req,res)=>{
    res.sendStatus(200)
})
moggoose.connect(process.env.mongoURI).then((res)=>console.log("Database connected")).catch((e)=>console.log(e))
app.listen(process.env.PORT || 3000,()=>console.log(`server Started http://localhost:${process.env.PORT}`))